services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/.n8n/n8n.sqlite
      - NODE_OPTIONS=--max-old-space-size=6144
    volumes:
      - ./n8n_data:/home/node/.n8n
    depends_on:
      - ollama
    networks:
      - n8n-net

  ollama:
    image: ollama/ollama:latest
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - n8n-net

  huggingface:
    image: ghcr.io/huggingface/text-generation-inference:latest
    platform: linux/amd64
    restart: always
    ports:
      - "8080:80"
    volumes:
      - huggingface_data:/data
    networks:
      - n8n-net

volumes:
  ollama_data:
  huggingface_data:

networks:
  n8n-net:
    driver: bridge