services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scheduler
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   ports:
  #     - "5051:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: rudy.design9@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: postgres
  #   volumes:
  #     - ./pgadmin_data:/var/lib/pgadmin
